version: "3.7"

services:
  web-back:
    container_name: django
    env_file: ./backend/web-back/.env
    build: ./backend/web-back/.
    volumes:
      - ./backend/web-back:/code/
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 config.wsgi:application --reload
    networks:
      - frontend_network
      - django_session
    environment:
      - OriginHost=localhost
      - CHOKIDAR_USEPOLLING=true
      - DJANGO_SETTINGS_MODULE=config.local_settings
      - redishost=redis_db
      - nginx_target=localhost:80
  redis_db:
    container_name: session_db
    image: redis:latest
    networks:
      - django_session
    ports:
      - "6379:6379"
  mysql_db:
    container_name: mysql
    build:
      context: ./mysql/.
      dockerfile: Dockerfile
    env_file:
      - mysql/mysql_env
    tty: true
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql/sql_dir:/sql_dir

  reverse_proxy:
    container_name: nginx_frontend
    build:
      context: ./nginx/.
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/html
    networks:
      - frontend_network
  test_auth_server:
    container_name: auth_temp
    build:
      context: ./auth_test/.
      dockerfile: Dockerfile
    environment:
      - nginx_target=127.0.0.1:80
    networks:
      - django_session
      - frontend_network
    volumes:
      - ./auth_test/django_server/test_auth:/django
    command: gunicorn --bind :8000 config.wsgi:application --reload
networks:
  django_session:
    driver: bridge
  frontend_network:
    driver: bridge
volumes:
  mysql_volume: