version: "3.7"

services:
  web-back:
    container_name: django
    env_file: ./backend/web-back/.env
    build: ./backend/web-back/.
    volumes:
      - ./backend/web-back:/code/
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 config.wsgi:application --reload
    networks:
      - django_session
      - auth_session
    environment:
      - ORIGIN_HOST=ec2-52-192-243-165.ap-northeast-1.compute.amazonaws.com
      - CHOKIDAR_USEPOLLING=true
      - DJANGO_SETTINGS_MODULE=config.local_settings
      - REDIS_HOST=52.192.243.165
  reverse_proxy:
    container_name: nginx_frontend
    build:
      context: ./nginx/.
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    networks:
      - django_session

  auth_server:
    container_name: nginx_auth
    build:
      context: ./auth_nginx/.
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth_nginx/html:/html
    ports:
      - 16000:80
      - 8080:80
    networks:
      - django_session
  redis_db:
      container_name: session_db
      image: redis:latest
      command: redis-server --requirepass Soc1@lStyle
      ports:
        - 6379:6379

networks:
  django_session:
    driver: bridge
  auth_session:
    driver: bridge
volumes:
  mysql_volume:
