# Generated by Django 3.0.5 on 2022-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cheer_ID', models.BigIntegerField()),
            ],
        ),
    ]
