# Generated by Django 3.0.5 on 2022-10-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialStyle',
            fields=[
                ('SocialStyle_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Type_Name', models.TextField()),
                ('Type_Explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cheer_ID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('Result_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Date', models.BigIntegerField()),
                ('SocialStyle_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialStyles.SocialStyle')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialStyles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Relational',
            fields=[
                ('Relational_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Relational_Description', models.TextField()),
                ('Relational_Type', models.BooleanField()),
                ('MySocialStyle_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_SS', to='socialStyles.SocialStyle')),
                ('TargetSocialStyle_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target_SS', to='socialStyles.SocialStyle')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profession_Name', models.TextField()),
                ('SocialStyleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialStyles.SocialStyle')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_Explanation', models.TextField()),
                ('SocialStyle_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialStyles.SocialStyle')),
            ],
        ),
    ]
