# Generated by Django 3.0.5 on 2022-10-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialStyles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialstyle',
            name='SocialStyle_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
