# Generated by Django 3.0.5 on 2022-11-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialStyles', '0003_auto_20221119_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('questions', models.TextField()),
                ('select_type', models.IntegerField()),
                ('pos', models.TextField()),
            ],
        ),
    ]
