# Generated by Django 3.0.5 on 2022-11-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialStyles', '0004_questions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
