# Generated by Django 3.0.5 on 2022-12-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialStyles', '0005_auto_20221123_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_type_name', models.TextField()),
                ('cheer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialStyles.User')),
            ],
            options={
                'db_table': 'latest_result',
            },
        ),
    ]
