# Generated by Django 3.0.5 on 2022-12-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialStyles', '0006_latestresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestresult',
            old_name='latest_type_name',
            new_name='latest_social_style_id',
        ),
    ]
