# Generated by Django 3.0.5 on 2022-12-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialStyles', '0007_auto_20221204_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='latestresult',
            name='cheer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='socialStyles.User'),
        ),
    ]
