# Generated by Django 3.0.5 on 2022-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialStyles', '0009_auto_20221204_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relational',
            name='my_social_style_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='relational',
            name='target_social_style_id',
            field=models.IntegerField(),
        ),
    ]
